host = "127.0.0.1"
port = 7788
backend = "etcd"
backend-address = "127.0.0.1:2379"
# cacert-file = "/path/to/ca.crt"
# cert-file = "/path/to/cert.crt"
# key-file = "/path/to/key.pem"

[logger]
filename = "tso.log"
format = "json"
level = "info"
max-size = 100
max-backups = 5
max-age = 30
compress = true